all:
	echo "use the respective tag names to compile different programs"

simple:
	g++ -std=c++11 simpleLambda.cpp -o simple.elf

lambda1:
	g++ -std=c++11 lambda1.cpp -o lambda1.elf

lambda2:
	g++ -std=c++11 lambda2.cpp -o lambda2.elf

clean:
	rm *.elf
